
package pe.com.unmsm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListParent", targetNamespace = "http://service.unmsm.com.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListParent {


    /**
     * 
     * @return
     *     returns java.util.List<pe.com.unmsm.service.Parent>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listParent", targetNamespace = "http://service.unmsm.com.pe/", className = "pe.com.unmsm.service.ListParent_Type")
    @ResponseWrapper(localName = "listParentResponse", targetNamespace = "http://service.unmsm.com.pe/", className = "pe.com.unmsm.service.ListParentResponse")
    @Action(input = "http://service.unmsm.com.pe/ListParent/listParentRequest", output = "http://service.unmsm.com.pe/ListParent/listParentResponse")
    public List<Parent> listParent();

}
