
package pe.com.unmsm.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListParentService", targetNamespace = "http://service.unmsm.com.pe/", wsdlLocation = "http://localhost:8080/parent?wsdl")
public class ListParentService
    extends Service
{

    private final static URL LISTPARENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTPARENTSERVICE_EXCEPTION;
    private final static QName LISTPARENTSERVICE_QNAME = new QName("http://service.unmsm.com.pe/", "ListParentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/parent?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTPARENTSERVICE_WSDL_LOCATION = url;
        LISTPARENTSERVICE_EXCEPTION = e;
    }

    public ListParentService() {
        super(__getWsdlLocation(), LISTPARENTSERVICE_QNAME);
    }

    public ListParentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTPARENTSERVICE_QNAME, features);
    }

    public ListParentService(URL wsdlLocation) {
        super(wsdlLocation, LISTPARENTSERVICE_QNAME);
    }

    public ListParentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTPARENTSERVICE_QNAME, features);
    }

    public ListParentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListParentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListParent
     */
    @WebEndpoint(name = "ListParentPort")
    public ListParent getListParentPort() {
        return super.getPort(new QName("http://service.unmsm.com.pe/", "ListParentPort"), ListParent.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListParent
     */
    @WebEndpoint(name = "ListParentPort")
    public ListParent getListParentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.unmsm.com.pe/", "ListParentPort"), ListParent.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTPARENTSERVICE_EXCEPTION!= null) {
            throw LISTPARENTSERVICE_EXCEPTION;
        }
        return LISTPARENTSERVICE_WSDL_LOCATION;
    }

}
